service: desafioDockdev

provider:
  name: aws 
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: get
          cors: true